name: sc
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - pip:
    - absl-py==2.3.1
    - accelerate==1.9.0
    - adjusttext==1.3.0
    - adpbulk==0.1.4
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - anndata==0.12.1
    - antlr4-python3-runtime==4.9.3
    - anyio==4.10.0
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - array-api-compat==1.12.0
    - arrow==1.3.0
    - arviz==0.22.0
    - async-lru==2.0.5
    - attrs==25.3.0
    - babel==2.17.0
    - beautifulsoup4==4.13.4
    - bleach==6.2.0
    - blitzgsea==1.3.54
    - cached-property==2.0.1
    - cell-eval==0.5.42
    - cell-gears==0.1.2
    - certifi==2025.8.3
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - chex==0.1.90
    - click==8.2.1
    - contourpy==1.3.3
    - cpa==0.4.1
    - crc32c==2.7.1
    - cycler==0.12.1
    - datasets==2.21.0
    - dcor==0.6
    - debugpy==1.8.15
    - defusedxml==0.7.1
    - deprecated==1.2.18
    - dill==0.3.8
    - docrep==0.3.2
    - docstring-parser==0.17.0
    - donfig==0.8.1.post1
    - einops==0.8.1
    - equinox==0.13.0
    - et-xmlfile==2.0.0
    - etils==1.13.0
    - fast-array-utils==1.2.1
    - fastjsonschema==2.21.1
    - filelock==3.18.0
    - flax==0.11.0
    - fonttools==4.59.0
    - formulaic==1.2.0
    - formulaic-contrasts==1.0.0
    - fqdn==1.5.1
    - frozenlist==1.7.0
    - fsspec==2024.6.1
    - grpcio==1.74.0
    - h11==0.16.0
    - h5netcdf==1.6.3
    - h5py==3.14.0
    - hf-xet==1.1.5
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.34.3
    - humanize==4.12.3
    - idna==3.10
    - igraph==0.11.9
    - importlib-resources==6.5.2
    - iniconfig==2.1.0
    - interface-meta==1.3.0
    - ipywidgets==8.1.7
    - isoduration==20.11.0
    - jax==0.6.2
    - jaxlib==0.6.2
    - jaxopt==0.8.5
    - jaxtyping==0.3.2
    - jinja2==3.1.6
    - joblib==1.5.1
    - json5==0.12.0
    - jsonpointer==3.0.0
    - jsonschema==4.25.0
    - jsonschema-specifications==2025.4.1
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - jupyter-events==0.12.0
    - jupyter-lsp==2.2.6
    - jupyter-server==2.16.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.4.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.15
    - kiwisolver==1.4.8
    - lamin-utils==0.15.0
    - lark==1.2.2
    - legacy-api-wrap==1.4.1
    - leidenalg==0.10.2
    - lightning==2.5.2
    - lightning-utilities==0.15.0
    - lineax==0.0.8
    - llvmlite==0.44.0
    - markdown==3.8.2
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.5
    - mdurl==0.1.2
    - mistune==3.1.3
    - ml-collections==1.1.0
    - ml-dtypes==0.5.3
    - mpmath==1.3.0
    - msgpack==1.1.1
    - mudata==0.3.2
    - multidict==6.6.3
    - multipledispatch==1.0.0
    - multiprocess==0.70.16
    - narwhals==2.0.1
    - natsort==8.4.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - networkx==3.5
    - notebook==7.4.5
    - notebook-shim==0.2.4
    - numba==0.61.2
    - numcodecs==0.16.1
    - numpy==2.2.6
    - numpyro==0.18.0
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - omegaconf==2.3.0
    - openpyxl==3.1.5
    - opt-einsum==3.4.0
    - optax==0.2.5
    - orbax==0.1.7
    - orbax-checkpoint==0.11.20
    - ott-jax==0.5.1
    - overrides==7.7.0
    - pandas==2.3.1
    - pandocfilters==1.5.1
    - patsy==1.0.1
    - pdex==0.1.21
    - pertpy==1.0.1
    - pillow==11.3.0
    - pluggy==1.6.0
    - ply==3.11
    - polars==1.32.0
    - pot==0.9.5
    - prometheus-client==0.22.1
    - propcache==0.3.2
    - protobuf==6.31.1
    - psutil==7.0.0
    - pubchempy==1.0.4
    - pyarrow==21.0.0
    - pycparser==2.22
    - pydeseq2==0.5.2
    - pydot==4.0.1
    - pynndescent==0.5.13
    - pyomo==6.9.2
    - pyparsing==3.2.3
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - pytest==8.4.1
    - python-json-logger==3.3.0
    - pytorch-lightning==1.9.5
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==27.0.1
    - rdkit==2025.3.5
    - referencing==0.36.2
    - requests==2.32.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rich==14.1.0
    - rpds-py==0.26.0
    - safetensors==0.5.3
    - scanpy==1.11.4
    - scgpt==0.2.4
    - scib==1.1.7
    - scikit-learn==1.7.1
    - scikit-misc==0.5.1
    - scipy==1.16.1
    - scvi-tools==0.20.3
    - seaborn==0.13.2
    - send2trash==1.8.3
    - session-info==1.0.1
    - session-info2==0.2
    - shtab==1.7.2
    - simplejson==3.20.1
    - sniffio==1.3.1
    - soupsieve==2.7
    - sparse==0.17.0
    - sparsecca==0.3.1
    - statsmodels==0.14.5
    - stdlib-list==0.11.1
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorstore==0.1.76
    - terminado==0.18.1
    - texttable==1.7.0
    - threadpoolctl==3.6.0
    - timm==1.0.19
    - tinycss2==1.4.0
    - tomlkit==0.13.3
    - toolz==1.0.0
    - torch==2.7.1
    - torch-geometric==2.6.1
    - torchaudio==2.7.1
    - torchdiffeq==0.2.5
    - torchinfo==1.8.0
    - torchmetrics==1.8.0
    - torchtext==0.18.0
    - torchvision==0.22.1
    - tornado==6.5.1
    - tqdm==4.67.1
    - treescope==0.1.9
    - triton==3.3.1
    - typeguard==4.4.4
    - types-python-dateutil==2.9.0.20250708
    - tyro==0.9.27
    - tzdata==2025.2
    - umap-learn==0.5.9.post2
    - uri-template==1.3.0
    - urllib3==2.5.0
    - wadler-lindig==0.1.7
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.1.3
    - widgetsnbextension==4.0.14
    - wrapt==1.17.2
    - xarray==2025.7.1
    - xarray-einstats==0.9.1
    - xxhash==3.5.0
    - yarl==1.20.1
    - zarr==3.1.1
prefix: /opt/conda/envs/sc
